version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "yearly"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "yearly"
