name: Install java
description: Installs java
runs:
  using: composite

  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && 'microsoft' || 'temurin '}}
        java-version: '17'
