name: Android

on:
  push:
    paths:
      - '**/android.yml'
  workflow_dispatch:

jobs:
  setup-android:
    name: setup-android (${{ matrix.container || matrix.os }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: ubuntu-latest
          # - os: ubuntu-latest
          #   container: ghcr.io/jpnurmi/alpine:3.21
          # - os: ubuntu-24.04-arm
          - os: windows-latest
          - os: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/dumpbin
        if: ${{ runner.os == 'Windows' }}

      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '21'

      # - uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
      #   with:
      #     log-accepted-android-sdk-licenses: false
      #     packages: "ndk;23.2.8568313"

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && 'microsoft' || 'temurin' }}
          java-version: '17'

      - name: Setup Android SDK
        #uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
        uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
        with:
          log-accepted-android-sdk-licenses: false
        # env:
        #   ANDROID_SDK_ROOT: C:\Android\android-sdk

      # - run: sdkmanager "build-tools;34.0.0"

      # - run: |
      #     dumpbin /headers (Join-Path $env:ANDROID_SDK_ROOT 'build-tools/34.0.0/aapt.exe')
      #     & (Join-Path $env:ANDROID_SDK_ROOT 'build-tools/34.0.0/aapt.exe') version
      #   if: ${{ runner.os == 'Windows' }}

      # - run: |
      #     file $ANDROID_SDK_ROOT/build-tools/34.0.0/aapt
      #     $ANDROID_SDK_ROOT/build-tools/34.0.0/aapt version
      #   if: ${{ runner.os == 'Linux' }}

      # - run: |
      #     tree $ANDROID_SDK_ROOT
