name: Android

on:
  push:
    paths: '**/android.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build-tools:
    runs-on: windows-11-arm

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: Get-Command java

      - uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
        with:
          log-accepted-android-sdk-licenses: false

      - run: sdkmanager --list
      - run: sdkmanager "build-tools;34.0.0"
      - run: tree ${env:ANDROID_SDK_ROOT}
      # - run: Get-Command aapk

      # - uses: lorenalexm/install-dumpbin-action@main

      - run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

          # Install Visual Studio Build Tools
          choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64" --no-progress

          # Set up PATH for Visual Studio
          $vsPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC"
          $latestVersion = (Get-ChildItem -Path $vsPath | Sort-Object Name -Descending | Select-Object -First 1).Name
          $dumpbinPath = "$vsPath\$latestVersion\bin\Hostx64\x64"
          echo $dumpbinPath >> $env:GITHUB_PATH
