name: Android

on:
  push:
    paths: '**/android.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build-tools:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dumpbin

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: Get-Command java
      - run: dumpbin /headers (Get-Command java).source

      - uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
        with:
          log-accepted-android-sdk-licenses: false

      - run: sdkmanager --list
      - run: sdkmanager "build-tools;34.0.0"
      #- run: tree ${env:ANDROID_SDK_ROOT}/build-tools/34.0.0 /F
      - run: dumpbin /headers ${env:ANDROID_SDK_ROOT}/build-tools/34.0.0/aapt.exe
