name: Build

on:
  push:
    paths: '**/build.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  sentry-native:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4
        with:
          repository: getsentry/sentry-native
          submodules: 'recursive'

      - run: cmake -B build -D CMAKE_BUILD_TYPE=RelWithDebInfo -D SENTRY_BACKEND=inproc -D SENTRY_BUILD_SHARED_LIBS=0
      - run: cmake --build build --parallel --target sentry

  sentry-dotnet:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4
        with:
          repository: getsentry/sentry-dotnet
          submodules: 'recursive'

      - run: ./scripts/build-sentry-native.ps1
