name: Cache

on:
  push:
    paths:
      - "**/cache.yml"
  workflow_dispatch:

jobs:
  save:
    runs-on: windows-11-arm

    steps:
      - run: echo "Hello from windows-11-arm" > hello.txt

      - name: Install winget
        run: |
          # Download winget and its dependencies from GitHub releases
          $wingetUrl = "https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
          $dependenciesUrl = "https://github.com/microsoft/winget-cli/releases/latest/download/DesktopAppInstaller_Dependencies.zip"
          
          # Download files
          Invoke-WebRequest -Uri $wingetUrl -OutFile "winget.msixbundle"
          Invoke-WebRequest -Uri $dependenciesUrl -OutFile "dependencies.zip"
          
          # Extract and install dependencies
          Expand-Archive -Path "dependencies.zip" -DestinationPath "dependencies"
          Get-ChildItem "dependencies" -Filter "*.appx" | ForEach-Object {
              Add-AppxPackage $_.FullName
          }
          
          # Install winget
          Add-AppxPackage "winget.msixbundle"
          
          # Add to GitHub Actions PATH
          echo "$env:LOCALAPPDATA\Microsoft\WindowsApps" >> $env:GITHUB_PATH
        shell: powershell

      #- run: choco install --debug --verbose zstandard
      - run: winget install Zstandard --accept-source-agreements --accept-package-agreements

      - uses: actions/cache@v4
        id: cache-hello
        with:
          path: hello.txt
          key: hello-key
          enableCrossOsArchive: true

  restore:
    needs: [save]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache/restore@v4
        with:
          path: hello.txt
          key: hello-key
          enableCrossOsArchive: true
          fail-on-cache-miss: true
