name: Cache

on:
  push:
    paths:
      - "**/cache.yml"
  workflow_dispatch:

jobs:
  save:
    runs-on: windows-11-arm

    steps:
      - run: echo "Hello from windows-11-arm" > hello.txt

      #- run: choco install --debug --verbose zstandard

      - shell: pwsh
        run: |
          $version = 'v1.5.7'
          $downloadUrl = "https://github.com/facebook/zstd/releases/download/v$version/zstd-v$version-win64.zip"

          Write-Host "Downloading zstd v$version"

          # Download and extract
          $zipPath = "$env:TEMP\zstd.zip"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $env:TEMP -Force

          # Copy binary to tools directory
          $targetDir = "C:\tools\zstd"
          New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
          Copy-Item "$env:TEMP\zstd-v$version-win64\zstd.exe" $targetDir -Force

          # Add to PATH
          echo "$targetDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          Write-Host "zstd installed successfully"

          # Verify installation
          & "$targetDir\zstd.exe" --version

      - uses: actions/cache@v4
        id: cache-hello
        with:
          path: hello.txt
          key: hello-key
          enableCrossOsArchive: true

  restore:
    needs: [save]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache/restore@v4
        with:
          path: hello.txt
          key: hello-key
          enableCrossOsArchive: true
          fail-on-cache-miss: true
