name: Cache

on:
  push:
    paths:
      - "**/cache.yml"
  workflow_dispatch:

jobs:
  save:
    runs-on: windows-11-arm

    steps:
      - run: echo "Hello from windows-11-arm" > hello.txt

      - name: Install zstd
        shell: pwsh
        run: |
          $version = '1.5.7'
          $installDir = "$env:RUNNER_TOOL_CACHE\zstd-v$version-win64"
          Invoke-WebRequest -OutFile "$env:TEMP\zstd.zip" -Uri "https://github.com/facebook/zstd/releases/download/v$version/zstd-v$version-win64.zip"
          Expand-Archive -Path "$env:TEMP\zstd.zip" -DestinationPath $env:RUNNER_TOOL_CACHE -Force
          echo "$installDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          & "$installDir\zstd.exe" --version

      - uses: actions/cache@v4
        id: cache-hello
        with:
          path: hello.txt
          key: hello-key
          enableCrossOsArchive: true

  restore:
    needs: [save]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache/restore@v4
        with:
          path: hello.txt
          key: hello-key
          enableCrossOsArchive: true
          fail-on-cache-miss: true
