name: Checkout

on:
  push:
    paths:
      - '**/checkout.yml'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: getsentry/sentry-dotnet
          submodules: recursive

      - run: ls -a

      - run: |
          mkdir -p src/Sentry/Release
          touch src/Sentry/Release/Sentry.5.11.0.nupkg
          touch src/Sentry/Release/Sentry.5.11.0.snunupkg

          mkdir -p src/Sentry.Fake/Release
          touch src/Sentry.Fake/Release/Sentry.Fake.5.11.0.nupkg
          touch src/Sentry.Fake/Release/Sentry.Fake.5.11.0.snunupkg

      - uses: actions/checkout@v4
        with:
          repository: getsentry/sentry-dotnet
          submodules: false
          sparse-checkout: |
            integration-test
            .github
          sparse-checkout-cone-mode: false
          clean: false

      - run: ls -a

      - run: tree
