name: Chrome

on:
  push:
    paths:
      - '**/chrome.yml'
  workflow_dispatch:

jobs:
  setup:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: browser-actions/setup-chrome@v2
        id: setup-chrome
        with:
          chrome-version: 141
          install-chromedriver: true

      - run: echo "chrome-version=${{ steps.setup-chrome.outputs.chrome-version }}"
      - run: echo "chrome-path=${{ steps.setup-chrome.outputs.chrome-path }}"
      - run: echo "chromedriver-version=${{ steps.setup-chrome.outputs.chromedriver-version }}"
      - run: echo "chromedriver-path=${{ steps.setup-chrome.outputs.chromedriver-path }}"

      - run: ${{ steps.setup-chrome.outputs.chromedriver-path }} --version
