name: Debug

on:
  push:
    paths: '**/debug.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  env:
    runs-on: windows-11-arm

    steps:
      - run: |
          dir env:

      - uses: actions/checkout@v4
        with:
          repository: getsentry/sentry-native
          submodules: 'recursive'

      - run: cmake -B build -D CMAKE_BUILD_TYPE=RelWithDebInfo -D SENTRY_BACKEND=inproc

      - run: cmake --build build --parallel
