name: Debug

on:
  push:
    paths: '**/debug.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  env:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4
      - run: |
          dir env:
      - run: |
          tree "$env:ProgramFiles" /F
      - run: |
          tree "$env:ProgramFiles(Arm)" /F
      - run: |
          tree "$env:ProgramFiles(X86)" /F
      - run: |
          tree "$env:RUNNER_TOOL_CACHE" /F
