name: Debug

on:
  push:
    paths: '**/debug.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  env:
    runs-on: windows-11-arm

    steps:
      - run: |
          dir env:

      # - run: |
      #     java -version
      #     dumpbin /headers (Get-Command java).Source | Select-String "machine"
      #   continue-on-error: true

      # - run: |
      #     python --version
      #     dumpbin /headers (Get-Command python).Source | Select-String "machine"
      #   continue-on-error: true

      # - run: |
      #     dotnet --version
      #     dumpbin /headers (Get-Command dotnet).Source | Select-String "machine"
      #   continue-on-error: true

      # - run: |
      #     ls ${env:ProgramFiles}
      # - run: |
      #     ls ${env:ProgramFiles(Arm)}
      # - run: |
      #     ls ${env:ProgramFiles(x86)}
      # - run: |
      #     ls ${env:RUNNER_TOOL_CACHE}

      # - run: |
      #     tree "${env:ProgramFiles}/Android" /F
      # - run: |
      #     tree "${env:ProgramFiles}/CMake" /F
      # - run: |
      #     tree "${env:ProgramFiles}/dotnet" /F
      # - run: |
      #     tree "${env:ProgramFiles}/OpenSSL" /F

      # - run: |
      #     tree ${env:ProgramFiles}
      # - run: |
      #     tree ${env:ProgramFiles(Arm)}
      # - run: |
      #     tree ${env:ProgramFiles(x86)}
      # - run: |
      #     tree ${env:RUNNER_TOOL_CACHE}

      # - run: |
      #     tree ${env:ProgramFiles} /F
      # - run: |
      #     tree ${env:ProgramFiles(Arm)} /F
      # - run: |
      #     tree ${env:ProgramFiles(x86)} /F
      # - run: |
      #     tree ${env:RUNNER_TOOL_CACHE} /F
