name: Docker

on:
  push:
    paths:
      - '**/docker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #   - uses: actions/setup-dotnet@v4
    #     with:
    #       dotnet-version: |
    #         9.0.301

    #   - uses: actions/download-artifact@v4
    #     with:
    #       # ${{ github.sha }}
    #       name: b47c4db022aff8e35579dec566d619dbd0542dc7
    #       path: src
    #       repository: getsentry/sentry-dotnet

      - run: |
          mkdir -p src/Sentry/bin/Release
          curl -L https://www.nuget.org/api/v2/package/Sentry/5.11.0 -o src/Sentry/bin/Release/Sentry.5.11.0.nupkg

      - name: Setup Local Source
        run: |
          mkdir local-packages
          cp src/Sentry/bin/Release/Sentry.*.nupkg local-packages/
          dotnet nuget add source $PWD/local-packages --name local-packages
          dotnet nuget list source

      - name: Setup Project
        run: |
          dotnet new console --aot --name helloworld
          dotnet add package Sentry --prerelease --source ./local-packages
          cat > Program.cs <<'EOF'
          SentrySdk.Init(options =>
          {
              options.Dsn = "https://foo@sentry.invalid/42";
              options.Debug = true;
          });
          Console.WriteLine("Hello, Sentry!");
          EOF

      - name: Publish Project
        run: dotnet publish -p:EnableSdkContainerSupport=true -t:PublishContainer

      - name: Run Docker Container
        run: docker run --rm helloworld
