name: Docker

on:
  push:
    paths:
      - '**/docker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.301

      - uses: actions/download-artifact@v4
        with:
          # ${{ github.sha }}
          name: b47c4db022aff8e35579dec566d619dbd0542dc7
          path: src
          repository: getsentry/sentry-dotnet

      - run: |
          dotnet new console -o HelloWorld --aot
          cd HelloWorld
          mkdir local-packages
          cp ../src/Sentry/bin/Release/Sentry.*.nupkg local-packages
          dotnet nuget add source ./local-packages
          dotnet add package Sentry --prerelease --source ./local-packages
          cat > Program.cs <<'EOF'
          SentrySdk.Init(options =>
          {
              options.Dsn = "https://foo@sentry.invalid/42";
              options.Debug = true;
          });
          Console.WriteLine("Hello, Sentry!");
          EOF
          dotnet publish -p:EnableSdkContainerSupport=true -t:PublishContainer -p:SentryNative=false

      - run: docker run --rm helloworld
