name: Dumpbin

on:
  push:
    paths: '**/dumpbin.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  dumpbin:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm]

    steps:
      - run: |
          dir env:

      - uses: .github/actions/dumpbin

      - run: |
          Get-Command dumpbin

      - run: |
          dumpbin /headers (Get-Command dumpbin).Source
