name: Flow

on:
  push:
    paths:
      - '**/flow.yml'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.no-mobile && 'Build and test' || 'Build' }} (${{ matrix.container || matrix.os }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: ubuntu-latest
            container: ubuntu:24.04
            no-mobile: true
          - os: ubuntu-latest
            container: ghcr.io/jpnurmi/alpine:3.21
            no-mobile: true

    steps:
      - uses: actions/checkout@v4

      - run: sleep 10s
        shell: bash
        if: ${{ runner.os == 'Linux' && !matrix.container }}

      - run: sleep 30s
        shell: bash
        if: ${{ runner.os == 'Windows' }}

      - name: Test
        uses: ./.github/actions/test
        if: ${{ matrix.no-mobile }}

  test:
    needs: [build]
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test

  publish:
    needs: [test]
    name: Publish
    runs-on: windows-latest

    steps:
      - run: echo "Published!"
        shell: bash
