name: GRDK

on:
  push:
    paths:
      - '**/grdk.yml'
  workflow_dispatch:

jobs:
  grdk:
    name: GRDK
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - name: Cache GDK
        id: cache-gdk
        uses: actions/cache@v4
        with:
          path: |
            "C:\Program Files (x86)\Microsoft GDK\250401"
            "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Platforms\Gaming.Desktop.x64\250401"
          key: gdk-250401

      - name: Search GDK
        run: winget search --accept-source-agreements Microsoft.Gaming.GDK

      - name: Install GDK
        if: steps.cache-gdk.outputs.cache-hit != 'true'
        run: winget install --accept-package-agreements --silent --disable-interactivity --version 2504.1.4046 Microsoft.Gaming.GDK

      - run: |
          dir env:

      - run: |
          dir "C:\Program Files (x86)\Microsoft GDK"
          dir "C:\Program Files (x86)\Microsoft GDK\250401"
          dir "C:\Program Files (x86)\Microsoft GDK\250401\GRDK"
        continue-on-error: true

      - run: |
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Platforms\Gaming.Desktop.x64"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Platforms\Gaming.Desktop.x64\250401"
        continue-on-error: true
