name: GRDK

on:
  push:
    paths:
      - '**/grdk.yml'
      - '**/setup-gdk/action.yml'
  workflow_dispatch:

jobs:
  grdk:
    name: GRDK
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          repository: getsentry/sentry-native
          ref: feat/grdk
          submodules: recursive

      - name: Setup GDK
        # uses: ./.github/actions/setup-gdk
        uses: jpnurmi/gha/.github/actions/setup-gdk@main
        with:
          gdk-version: 2504.1.4046

      - name: Build
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A "Gaming.Desktop.x64" -DCMAKE_TOOLCHAIN_FILE="./toolchains/xbox/grdk_toolchain.cmake" -DGDK_VERSION="250401"
          cmake --build build
