name: GRDK

on:
  push:
    paths:
      - '**/grdk.yml'
  workflow_dispatch:

jobs:
  grdk:
    name: GRDK
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      # - name: Cache GDK
      #   id: cache-gdk
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       "C:/Program Files (x86)/Microsoft GDK/250401"
      #       "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Microsoft/VC/v170/Platforms/Gaming.Desktop.x64/250401"
      #     key: gdk-250401

      # - name: Search GDK
      #   run: winget search --accept-source-agreements Microsoft.Gaming.GDK

      # - name: Install GDK
      #   if: steps.cache-gdk.outputs.cache-hit != 'true'
      #   run: winget install --accept-package-agreements --silent --disable-interactivity --version 2504.1.4046 Microsoft.Gaming.GDK

      - name: Restore GDK
        id: cache-gdk
        uses: actions/cache/restore@v4
        with:
          path: GDK_2504.1.4046.zip
          key: gdk-2504.1.4046

      - name: Download GDK
        if: steps.cache-gdk.outputs.cache-hit != 'true'
        run: |
          curl -L -O https://github.com/microsoft/GDK/releases/download/April-2025-Update-1-v2504.1.4046/GDK_2504.1.4046.zip

      - name: Cache GDK
        if: steps.cache-gdk.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: GDK_2504.1.4046.zip
          key: gdk-2504.1.4046

      - name: Install GDK
        run: |
          unzip -q GDK_2504.1.4046.zip -d gdk
          gdk\PGDK.exe /features + /q /log gdk.log

      - run: |
          type gdk.log

      - run: |
          dir env:

      - run: |
          dir "C:\Program Files (x86)\Microsoft GDK"
          dir "C:\Program Files (x86)\Microsoft GDK\250401"
          dir "C:\Program Files (x86)\Microsoft GDK\250401\GRDK"
        continue-on-error: true

      - run: |
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Platforms\Gaming.Desktop.x64"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Platforms\Gaming.Desktop.x64\250401"
        continue-on-error: true
