name: GRDK

on:
  push:
    paths:
      - '**/grdk.yml'
  workflow_dispatch:

jobs:
  grdk:
    name: GRDK (${{ matrix.container || matrix.os }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025

    steps:
      - run: winget search --accept-source-agreements Microsoft.Gaming.GDK
      - run: winget install --accept-package-agreements --silent --disable-interactivity --version 2504.1.4046 Microsoft.Gaming.GDK
