name: GRDK

on:
  push:
    paths:
      - '**/grdk.yml'
  workflow_dispatch:

jobs:
  grdk:
    name: GRDK
    runs-on: windows-2025

    steps:
      - run: winget search --accept-source-agreements Microsoft.Gaming.GDK

      - run: winget install --accept-package-agreements --silent --disable-interactivity --version 2504.1.4046 Microsoft.Gaming.GDK

      - run: |
          dir "C:\Program Files (x86)\Microsoft GDK\250401\GRDK"

      - run: |
          dir "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Platforms"
