name: Input

on:
  push:
    paths:
      - '**/input.yml'
  workflow_dispatch:
    inputs:
      versions:
        description: 'Versions'
        required: false
        default: '*'
        type: string

env:
  ALL_VERSIONS: '["240307", "240602", "240603", "250401"]'

jobs:
  select:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.version.outputs.versions }}
    steps:
      - id: version
        run: |
          pattern="${{ github.event.inputs.versions || '*' }}"
          selected=$(jq --arg pat "$pattern" \
            '[.[] | select(test("^" + ($pat | gsub("\\*"; ".*") | gsub("\\?"; ".")) + "$"))]' \
            <<< '${{ env.ALL_VERSIONS }}')

          echo "Selected: $selected"
          echo "versions=$selected" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: select
    strategy:
      matrix:
        version: ${{ fromJson(needs.select.outputs.versions) }}

    steps:
      - run: |
          echo "Version: ${{ matrix.version }}"
