name: Input

on:
  push:
    paths:
      - '**/input.yml'
  workflow_dispatch:
    inputs:
      versions:
        description: 'Versions'
        required: false
        default: '*'
        type: string

env:
  ALL_VERSIONS: '["240307", "240602", "240603", "250401"]'

jobs:
  select:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.version.outputs.versions }}
    steps:
      - id: version
        run: |
          versions=$(jq --arg versions '${{ inputs.versions }}' '[.[] | select(test("^" + ($versions | gsub("\\*"; ".*") | gsub("\\?"; ".")) + "$"))]' <<< $ALL_VERSIONS)
          echo 'versions=$versions' >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: select
    strategy:
      matrix:
        version: ${{ needs.select.outputs.versions }}

    steps:
      - run: |
          echo "Version: ${{ matrix.version }}"
