name: Input

on:
  push:
    paths:
      - '**/input.yml'
  workflow_dispatch:
    inputs:
      versions:
        description: 'Test GDK version(s) (e.g. 250401, 24*, or 25??01)'
        required: false
        default: '*'
        type: string

env:
  ALL_VERSIONS: '["240307", "240602", "240603", "250401"]'

jobs:
  select:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.version.outputs.versions }}
    steps:
      - id: version
        run: |
          echo "Env versions: ${{ env.ALL_VERSIONS }}"
          echo "Vars versions: ${{ vars.GDK_VERSIONS }}"

          pattern="${{ github.event.inputs.versions || '*' }}"
          versions=$(jq -c --arg pat "$pattern" \
            '[.[] | select(test("^" + ($pat | gsub("\\*"; ".*") | gsub("\\?"; ".")) + "$"))]' \
            <<< '${{ env.ALL_VERSIONS }}')
          echo "versions=$versions" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: select
    strategy:
      matrix:
        version: ${{ fromJson(needs.select.outputs.versions) }}

    steps:
      - run: |
          echo "Version: ${{ matrix.version }}"
