name: Java

on:
  push:
    paths:
      - '**/java.yml'
  workflow_dispatch:

jobs:
  setup-java:
    name: setup-java ${{ matrix.java-version }} (${{ matrix.os.container || matrix.os.host }}, ${{ matrix.java-distribution }})
    runs-on: ${{ matrix.os.host }}
    container: ${{ matrix.os.container }}
    strategy:
      fail-fast: false
      matrix:
        java-distribution: [temurin, microsoft]
        java-version: [17, 21]
        os:
          - host: ubuntu-latest
          - host: ubuntu-24.04-arm
          - host: ubuntu-latest
            container: ghcr.io/jpnurmi/alpine:3.21
          - host: windows-latest
          - host: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/dumpbin
        if: ${{ runner.os == 'Windows' }}

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}

      - run: |
          Get-Command java
          dumpbin /headers (Get-Command java).source
        shell: pwsh
        if: ${{ runner.os == 'Windows' }}

      - run: |
          file $JAVA_HOME/bin/java
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
        shell: bash
        if: ${{ runner.os == 'Linux' }}

      - run: java -version

      - name: Setup Android SDK
        #uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
        #uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
