name: Linux

on:
  push:
    paths:
      - '**/linux.yml'
  workflow_dispatch:

jobs:
  build:
    name: Linux (${{ matrix.os }}, ${{ matrix.container.image }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
          - os: ubuntu-24.04
            container:
              image: ghcr.io/jpnurmi/alpine:3.21
          - os: ubuntu-24.04
            container:
              image: ghcr.io/jpnurmi/alpine:3.22
          - os: ubuntu-24.04-arm
            container:
              image: ghcr.io/jpnurmi/alpine:3.21
              volumes: [/opt/node:/__e/node20]
          - os: ubuntu-24.04-arm
            container:
              image: ghcr.io/jpnurmi/alpine:3.22
              volumes: [/opt/node:/__e/node20]

    steps:
      - run: |
          ls -la /etc/*release

      - run: |
          cat /etc/*release

      - uses: actions/checkout@v4
