name: Linux

on:
  push:
    paths:
      - '**/linux.yml'
  workflow_dispatch:

jobs:
  build:
    name: Linux (${{ matrix.os.container || matrix.os.host }})
    runs-on: ${{ matrix.os.host }}
    container: ${{ matrix.os.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
          - os: ubuntu-24.04
            container: ghcr.io/jpnurmi/sentry-dotnet-alpine:3.21
          - os: ubuntu-24.04-arm
            container: ghcr.io/jpnurmi/sentry-dotnet-alpine:3.21

    steps:
      - run: |
          cat /etc/*release
      - uses: actions/checkout@v4
