name: Linux

on:
  push:
    paths:
      - '**/linux.yml'
  workflow_dispatch:

jobs:
  build:
    name: Linux (${{ matrix.os }}, ${{ matrix.container }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
          - os: ubuntu-24.04
            container: ghcr.io/jpnurmi/alpine:3.21
          - os: ubuntu-24.04
            container: ghcr.io/jpnurmi/alpine:3.22

          # actions/checkout:
          # > Error: JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
          # https://github.com/actions/runner/blob/0d24afa114c2ee4b6451e35f2ba2cb9b96955789/src/Runner.Worker/Handlers/StepHost.cs#L268-L274
          - os: ubuntu-24.04-arm
            container: ghcr.io/jpnurmi/alpine:3.21
          - os: ubuntu-24.04-arm
            container: ghcr.io/jpnurmi/alpine:3.22

    steps:
      - run: |
          cat /etc/os-release
          ls -la /etc/os-release

      - run: |
          sudo sed -i 's/ID=alpine/ID=unknown/' /etc/os-release

      - run: |
          which node
          node --version

      - run: |
          mv /__e/node20 /__e/node20.bak
        if: ${{ matrix.container }}

      - uses: actions/checkout@v4
