name: Mac

on:
  push:
    paths:
      - '**/mac.yml'
  workflow_dispatch:

jobs:
  env:
    name: Mac
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: macos-13
          - os: macos-14
          - os: macos-15
          - os: macos-15-intel
          - os: macos-15-large
          - os: macos-15-xlarge
          - os: macos-26
          - os: macos-26-intel
          - os: macos-26-large
          - os: macos-26-xlarge

    steps:
      - run: sysctl -n machdep.cpu.brand_string
      - run: xcodebuild -showsdks
