name: Python

on:
  push:
    paths:
      - '**/python.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  setup-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dumpbin

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # Error: Cache folder path is retrieved for pip but doesn't exist on disk: c:\users\runneradmin\appdata\local\pip\cache.
          # This likely indicates that there are no dependencies to cache. Consider removing the cache step if it is not needed.
          # cache: "pip"

      - run: Get-Command python3
      - run: dumpbin /headers (Get-Command python3).Source
      - run: python3 --version
