name: Python

on:
  push:
    paths:
      - '**/python.yml'
  workflow_dispatch:

jobs:
  setup-python:
    name: setup-python (${{ matrix.container || matrix.os }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-latest
            container: ghcr.io/jpnurmi/alpine:3.21
          - os: ubuntu-24.04-arm
          - os: windows-latest
          - os: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/dumpbin
        if: ${{ runner.os == 'Windows' }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # Error: Cache folder path is retrieved for pip but doesn't exist on disk: c:\users\runneradmin\appdata\local\pip\cache.
          # This likely indicates that there are no dependencies to cache. Consider removing the cache step if it is not needed.
          # cache: "pip"

      - run: |
          Get-Command python3
          dumpbin /headers (Get-Command python3).Source
        shell: pwsh
        if: ${{ runner.os == 'Windows' }}

      - run: |
          which python3
          file $(realpath $(which python3))
        shell: bash
        if: ${{ runner.os == 'Linux' }}

      - run: python3 --version
