name: Self-hosted

on:
  push:
    paths:
      - '**/self-hosted.yml'
  workflow_dispatch:

jobs:
  self-hosted:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: tree -a
