name: sentry-dotnet

on:
  push:
    paths:
      - '**/sentry-dotnet.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dumpbin

      - uses: actions/checkout@v4
        with:
          repository: getsentry/sentry-dotnet
          submodules: 'recursive'
          path: sentry-dotnet

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
        with:
          log-accepted-android-sdk-licenses: false

      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '11'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.203

      - run: ./scripts/build-sentry-native.ps1
        working-directory: sentry-dotnet

      - run: dumpbin modules/sentry-native/build/RelWithDebInfo/sentry.lib
        working-directory: sentry-dotnet
