name: Setup Java

on:
  push:
    paths:
      - '**/setup-java.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  setup-java:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm]
        java-version: [17, 21]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dumpbin

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && 'microsoft' || 'temurin '}}
          java-version: ${{ matrix.java-version }}

      - run: Get-Command java
      - run: dumpbin /headers (Get-Command java).source
      - run: java -version
