name: Setup Java

on:
  push:
    paths:
      - '**/setup-java.yml'
  workflow_dispatch:

jobs:
  setup-java:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, windows-11-arm]
        java-version: [17, 21]
        java-distribution: ['temurin', 'microsoft']
        include:
          - os: ubuntu-latest
          - os: ubuntu-latest
            container: alpine:3.21

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/dumpbin
        if: ${{ runner.os == 'Windows' }}

      - run: apk update && apk add file tree
        if: ${{ contains(matrix.container, 'alpine') }}

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}

      - run: |
          Get-Command java
          dumpbin /headers (Get-Command java).source
        shell: pwsh
        if: ${{ runner.os == 'Windows' }}

      - run: |
          file $JAVA_HOME/bin/java
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
        shell: bash
        if: ${{ runner.os == 'Linux' }}

      - run: java -version
