name: Setup Java

on:
  push:
    paths:
      - '**/setup-java.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  setup-java:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dumpbin

      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '21'

      - uses: ./.github/actions/java

      - run: Get-Command java
      - run: dumpbin /headers (Get-Command java).source
      - run: java -version
