name: VS

on:
  push:
    paths:
      - '**/vs.yml'
  workflow_dispatch:

jobs:
  # vswhere:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         # - os: windows-2019
  #         - os: windows-2022
  #         - os: windows-2025

  #   steps:
  #     - run: |
  #         & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
  #         # $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -property installationPath
  #         # echo "VS installation path: $vsPath"
  #         # dir $vsPath
  #         # dir "$vsPath\MSBuild\Microsoft\VC\v170\Platforms"
  #         # dir -Recurse "$vsPath\MSBuild\Microsoft\VC"

  vs2019:
    runs-on: windows-2022
    steps:
      - run: choco install visualstudio2019buildtools

      - uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[16.0,17.0)'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.408

      - run: dotnet new globaljson --sdk-version 5.0.408
      - run: dotnet --version
      - run: dotnet new console --name hello-sentry --output .
      - run: dotnet add package Sentry
      #- run: dotnet workload restore
      - run: msbuild hello-sentry.csproj -t:Restore,Build -p:Configuration=Release -v:normal
