name: VS

on:
  push:
    paths:
      - '**/vs.yml'
  workflow_dispatch:

jobs:
  env:
    name: VS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
          - os: windows-2025

    steps:
      - run: |
          & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -property installationPath
          echo "VS installation path: $vsPath"
          dir $vsPath
          dir "$vsPath\MSBuild\Microsoft\VC\v170\Platforms"
          dir -Recurse "$vsPath\MSBuild\Microsoft\VC"
