name: Windows

on:
  push:
    paths:
      - '**/windows.yml'
  workflow_dispatch:

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
          - os: windows-2022
          - os: windows-11-arm

    steps:
      - run: where cmd.exe
        shell: cmd

      - run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productLineVersion
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationVersion
        shell: cmd

      - run: |
          where.exe wmic.exe
